---
- name: Reload ssh
  ansible.builtin.systemd_service:
    name: ssh.service
    state: reloaded

- name: Restart chrony
  ansible.builtin.systemd_service:
    name: chrony.service
    state: restarted

- name: Apply sysctl
  ansible.builtin.command: /usr/sbin/sysctl --system
  changed_when: true
