[package]
name = "mako-billing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
mako-api = { path = "../mako-api" }
mako-gateway = { path = "../mako-gateway" }
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
