[Unit]
ConditionPathExists=/etc/mako/credentials/alert-smtp-password

[Service]
LoadCredential=alert-smtp-password:/etc/mako/credentials/alert-smtp-password
NoNewPrivileges=yes
CapabilityBoundingSet=
AmbientCapabilities=
PrivateDevices=yes
PrivateIPC=yes
PrivateTmp=yes
ProtectClock=yes
ProtectControlGroups=yes
ProtectHome=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectSystem=strict
ReadWritePaths=/var/lib/prometheus/alertmanager
LockPersonality=yes
MemoryDenyWriteExecute=yes
RemoveIPC=yes
RestrictAddressFamilies=AF_UNIX AF_INET
RestrictNamespaces=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
IPAddressDeny=any
IPAddressAllow=localhost
IPAddressAllow=any
DevicePolicy=closed
TasksMax=128
MemoryMax=256M
CPUQuota=50%
