// Types only, deliberately. The runtime hands this module's emitted JavaScript
// to every user worker as the first-party `@mako-cloud/edge-sdk`
// (`packages/cli/runtime/main/edge-sdk-source.ts`, generated by
// `scripts/build-runtime-module.mjs`), and a worker has no npm and no network,
// so that emit must have no imports at all. Every runtime check the SDK needs
// is therefore defined below rather than borrowed.
import type { ApiErrorEnvelope, ErrorCode, RetryAdvice, components } from "@mako-cloud/api-types";

export const PACKAGE_NAME = "@mako-cloud/edge-sdk" as const;

export type JsonObject = Record<string, unknown>;
type AuthUser = components["schemas"]["AuthUser"];
type WireDocument = components["schemas"]["DocumentRecord"];
type WireMutation = components["schemas"]["DocumentMutationRequest"];
type WireMutationResult = components["schemas"]["DocumentMutationResult"];
type WireAppMetadataUpdate = components["schemas"]["ServiceAppMetadataUpdate"];
export type FunctionDocumentQuery = components["schemas"]["DocumentQueryRequest"];
/**
 * A one-level JSON merge patch over a user's administrator-controlled app
 * metadata: a key set to `null` is removed, any other key replaces the stored
 * value whole.
 */
export type FunctionAppMetadataPatch = WireAppMetadataUpdate["appMetadata"];
export type FunctionAppMetadataResult = components["schemas"]["ServiceAppMetadataResult"];

export type FunctionDocument<T extends JsonObject = JsonObject> = Omit<WireDocument, "body"> & {
  readonly body: T;
};

export type FunctionDocumentMutation<T extends JsonObject = JsonObject> = Omit<
  WireMutation,
  "body"
> & {
  readonly body: T;
};

export type FunctionDocumentMutationResult<T extends JsonObject = JsonObject> = Omit<
  WireMutationResult,
  "document"
> & {
  readonly document: FunctionDocument<T> | null;
};

export interface FunctionDocumentQueryPage<T extends JsonObject = JsonObject> {
  readonly documents: FunctionDocument<T>[];
  readonly nextCursor: string | null;
}

export interface FunctionClientOptions {
  /** Internal Mako API origin injected by the runtime. */
  readonly endpoint: string | URL;
  readonly projectId: string;
  readonly environmentId: string;
  /** Verified raw caller token from the runtime, or null for a public invocation. */
  readonly callerAuthorization: string | null;
  readonly requestId?: string;
  readonly fetch?: typeof globalThis.fetch;
}

export interface RuntimeFunctionClientOptions
  extends Omit<FunctionClientOptions, "callerAuthorization" | "requestId"> {
  /** Function request supplied by the hosted or local Mako runtime. */
  readonly request: Request;
}

export interface ServiceFunctionClientOptions {
  /** Internal Mako API origin injected by the runtime. */
  readonly endpoint: string | URL;
  readonly projectId: string;
  readonly environmentId: string;
  /** A service credential read from an explicitly attached function secret. */
  readonly serviceCredential: string;
  /** Required audit reason recorded for every privileged operation. */
  readonly reason: string;
  /** Runtime request identifier used to correlate the bypass audit event. */
  readonly requestId: string;
  readonly fetch?: typeof globalThis.fetch;
}

export interface FunctionAuthClient {
  /** Returns the application user represented by the verified invoking token. */
  getUser(): Promise<AuthUser>;
  /** Revokes the session represented by the verified invoking token. */
  signOut(): Promise<void>;
}

export interface FunctionDocumentClient<T extends JsonObject = JsonObject> {
  get(documentId: string): Promise<FunctionDocument<T> | null>;
  query(query: FunctionDocumentQuery): Promise<FunctionDocumentQueryPage<T>>;
  mutate(
    documentId: string,
    mutation: FunctionDocumentMutation<T>,
  ): Promise<FunctionDocumentMutationResult<T>>;
}

export interface FunctionClient {
  readonly auth: FunctionAuthClient;
  documents<T extends JsonObject = JsonObject>(collectionId: string): FunctionDocumentClient<T>;
}

/** What a write may require of the value it is replacing. */
export interface SetAppMetadataOptions {
  /** Audited bypass reason; the client's configured one when omitted. */
  readonly reason?: string;
  /**
   * The user authorization epoch this patch was composed against -- the one
   * `getAppMetadata` returned. The write is refused with `conflict` if the
   * user's epoch has moved since, so two concurrent changes to one claim map
   * cannot silently keep whichever wrote last.
   */
  readonly expectedAuthorizationEpoch?: number;
}

export interface ServiceUserClient {
  /**
   * Reads a user's administrator-controlled app metadata through the audited
   * service route, with the authorization epoch it was read at. The patch a
   * write carries replaces a key whole, so a function that manages one member
   * of a claim map composes the next value out of this one and hands the
   * epoch back to `setAppMetadata`. The service credential must be scoped to
   * the reserved `users` target with the `read` operation.
   */
  getAppMetadata(userId: string, reason?: string): Promise<FunctionAppMetadataResult>;
  /**
   * Sets a user's administrator-controlled app metadata -- the claims the
   * user's next token carries and policies trust -- through the audited
   * service route. `reason` defaults to the client's configured reason. The
   * service credential must be scoped to the reserved `users` target with the
   * `update` operation.
   */
  setAppMetadata(
    userId: string,
    patch: FunctionAppMetadataPatch,
    options?: string | SetAppMetadataOptions,
  ): Promise<FunctionAppMetadataResult>;
}

export interface ServiceFunctionClient {
  documents<T extends JsonObject = JsonObject>(collectionId: string): FunctionDocumentClient<T>;
  readonly users: ServiceUserClient;
}

export class MakoEdgeSdkError extends Error {
  override readonly name: string = "MakoEdgeSdkError";
  readonly code?: ErrorCode;
  readonly requestId?: string;
  readonly retry?: RetryAdvice;
  readonly status?: number;

  constructor(
    message: string,
    options: {
      readonly apiError?: ApiErrorEnvelope;
      readonly status?: number;
    } = {},
  ) {
    super(message);
    if (options.apiError !== undefined) {
      this.code = options.apiError.error.code;
      this.requestId = options.apiError.error.requestId;
      this.retry = options.apiError.error.retry;
    }
    if (options.status !== undefined) {
      this.status = options.status;
    }
  }
}

export class MakoCallerIdentityRequiredError extends MakoEdgeSdkError {
  override readonly name: string = "MakoCallerIdentityRequiredError";
}

/**
 * Creates a tenant-bound client whose auth and document calls always forward
 * the verified invoking identity. Public invocations fail closed on first use.
 */
export function createFunctionClient(options: FunctionClientOptions): FunctionClient {
  const transport = new MakoTransport(options, {
    kind: "caller",
    value: validateCallerAuthorization(options.callerAuthorization),
  });
  return {
    auth: {
      getUser: () => transport.request<AuthUser>("auth/user", "GET"),
      signOut: () => transport.request<void>("auth/signout", "POST"),
    },
    documents: <T extends JsonObject = JsonObject>(collectionId: string) =>
      new DocumentClient<T>(transport, "collections", validateCollectionId(collectionId)),
  };
}

/** Creates the default caller client directly from the trusted runtime headers. */
export function createFunctionClientFromRequest(
  options: RuntimeFunctionClientOptions,
): FunctionClient {
  const callerAuthorization = options.request.headers.get("x-mako-caller-authorization");
  const requestId = options.request.headers.get("x-mako-request-id") ?? undefined;
  return createFunctionClient({
    endpoint: options.endpoint,
    projectId: options.projectId,
    environmentId: options.environmentId,
    callerAuthorization,
    ...(requestId === undefined ? {} : { requestId }),
    ...(options.fetch === undefined ? {} : { fetch: options.fetch }),
  });
}

/**
 * Explicitly creates a privileged document client from an attached service
 * credential. The dedicated service route verifies scope and audits the reason.
 */
export function createServiceClient(options: ServiceFunctionClientOptions): ServiceFunctionClient {
  const configuredReason = validateBypassReason(options.reason);
  const transport = new MakoTransport(options, {
    kind: "service",
    value: validateServiceCredential(options.serviceCredential),
    reason: configuredReason,
  });
  return {
    documents: <T extends JsonObject = JsonObject>(collectionId: string) =>
      new DocumentClient<T>(transport, "service/collections", validateCollectionId(collectionId)),
    users: {
      getAppMetadata: async (userId, reason) => {
        validateApplicationUserId(userId);
        const bypassReason = reason === undefined ? configuredReason : validateBypassReason(reason);
        return transport.request<FunctionAppMetadataResult>(
          `service/users/${encodeURIComponent(userId)}/app-metadata`,
          "GET",
          undefined,
          { "X-Mako-Bypass-Reason": bypassReason },
        );
      },
      setAppMetadata: async (userId, patch, options) => {
        validateApplicationUserId(userId);
        validateAppMetadataPatch(patch);
        const settings: SetAppMetadataOptions =
          typeof options === "string" ? { reason: options } : (options ?? {});
        const bypassReason =
          settings.reason === undefined ? configuredReason : validateBypassReason(settings.reason);
        const expected = settings.expectedAuthorizationEpoch;
        if (expected !== undefined && (!Number.isSafeInteger(expected) || expected < 0)) {
          throw new MakoEdgeSdkError("expected authorization epoch must be a non-negative integer");
        }
        const body: WireAppMetadataUpdate = {
          reason: bypassReason,
          appMetadata: patch,
          ...(expected === undefined ? {} : { expectedAuthorizationEpoch: expected }),
        };
        return transport.request<FunctionAppMetadataResult>(
          `service/users/${encodeURIComponent(userId)}/app-metadata`,
          "POST",
          body,
          { "X-Mako-Bypass-Reason": bypassReason },
        );
      },
    },
  };
}

interface Transport {
  request<T>(
    path: string,
    method: "GET" | "POST",
    body?: unknown,
    extraHeaders?: Readonly<Record<string, string>>,
  ): Promise<T>;
}

class DocumentClient<T extends JsonObject> implements FunctionDocumentClient<T> {
  readonly #transport: Transport;
  readonly #routePrefix: string;
  readonly #collectionId: string;

  constructor(transport: Transport, routePrefix: string, collectionId: string) {
    this.#transport = transport;
    this.#routePrefix = routePrefix;
    this.#collectionId = collectionId;
  }

  async get(documentId: string): Promise<FunctionDocument<T> | null> {
    const path = this.#documentPath(documentId);
    try {
      return await this.#transport.request<FunctionDocument<T>>(path, "GET");
    } catch (error) {
      if (error instanceof MakoEdgeSdkError && error.status === 404) {
        return null;
      }
      throw error;
    }
  }

  query(query: FunctionDocumentQuery): Promise<FunctionDocumentQueryPage<T>> {
    validateQuery(query);
    return this.#transport.request<FunctionDocumentQueryPage<T>>(
      `${this.#routePrefix}/${encodeURIComponent(this.#collectionId)}/documents/query`,
      "POST",
      query,
    );
  }

  mutate(
    documentId: string,
    mutation: FunctionDocumentMutation<T>,
  ): Promise<FunctionDocumentMutationResult<T>> {
    validateMutation(mutation);
    return this.#transport.request<FunctionDocumentMutationResult<T>>(
      this.#documentPath(documentId),
      "POST",
      mutation,
      { "Idempotency-Key": mutation.mutationId },
    );
  }

  #documentPath(documentId: string): string {
    validateDocumentId(documentId);
    return `${this.#routePrefix}/${encodeURIComponent(
      this.#collectionId,
    )}/documents/${encodeURIComponent(documentId)}`;
  }
}

type TransportCredential =
  | { readonly kind: "caller"; readonly value: string | null }
  | { readonly kind: "service"; readonly value: string; readonly reason: string };

class MakoTransport implements Transport {
  readonly #endpoint: URL;
  readonly #projectId: string;
  readonly #environmentId: string;
  readonly #credential: TransportCredential;
  readonly #requestId: string | undefined;
  readonly #fetch: typeof globalThis.fetch;

  constructor(
    options: FunctionClientOptions | ServiceFunctionClientOptions,
    credential: TransportCredential,
  ) {
    this.#endpoint = parseEndpoint(options.endpoint);
    this.#projectId = validateProjectId(options.projectId);
    this.#environmentId = validateEnvironmentId(options.environmentId);
    this.#credential = credential;
    this.#requestId = validateRequestId(options.requestId);
    this.#fetch = options.fetch ?? globalThis.fetch;
  }

  async request<T>(
    path: string,
    method: "GET" | "POST",
    body?: unknown,
    extraHeaders: Readonly<Record<string, string>> = {},
  ): Promise<T> {
    if (this.#credential.kind === "caller" && this.#credential.value === null) {
      throw new MakoCallerIdentityRequiredError(
        "this operation requires an authenticated function caller",
      );
    }
    const headers = new Headers({ Accept: "application/json" });
    if (this.#credential.kind === "caller") {
      headers.set("Authorization", `Bearer ${this.#credential.value}`);
    } else {
      headers.set("X-Mako-Service-Key", this.#credential.value);
      headers.set("X-Mako-Bypass-Reason", this.#credential.reason);
    }
    if (body !== undefined) {
      headers.set("Content-Type", "application/json");
    }
    if (this.#requestId !== undefined) {
      headers.set("X-Mako-Request-Id", this.#requestId);
    }
    // Per-call headers are set last so a call can narrow a default, such as
    // the bypass reason a single privileged write is audited under.
    for (const [name, value] of Object.entries(extraHeaders)) {
      headers.set(name, value);
    }
    let encodedBody: string | undefined;
    try {
      encodedBody = body === undefined ? undefined : JSON.stringify(body);
    } catch {
      throw new MakoEdgeSdkError("function SDK request is not JSON serializable");
    }
    let response: Response;
    try {
      const requestInit: RequestInit = { method, headers };
      if (encodedBody !== undefined) {
        requestInit.body = encodedBody;
      }
      response = await this.#fetch(new Request(this.#url(path), requestInit));
    } catch {
      throw new MakoEdgeSdkError("Mako service is unavailable");
    }
    if (!response.ok) {
      const responseBody: unknown = await response.json().catch(() => null);
      if (isApiErrorEnvelope(responseBody)) {
        throw new MakoEdgeSdkError(responseBody.error.message, {
          apiError: responseBody,
          status: response.status,
        });
      }
      throw new MakoEdgeSdkError("Mako service request failed", { status: response.status });
    }
    if (response.status === 204) {
      return undefined as T;
    }
    try {
      return (await response.json()) as T;
    } catch {
      throw new MakoEdgeSdkError("Mako service returned an invalid response", {
        status: response.status,
      });
    }
  }

  #url(path: string): URL {
    return new URL(
      `v1/projects/${encodeURIComponent(this.#projectId)}/environments/${encodeURIComponent(
        this.#environmentId,
      )}/${path}`,
      this.#endpoint,
    );
  }
}

function parseEndpoint(value: string | URL): URL {
  let endpoint: URL;
  try {
    endpoint = new URL(value);
  } catch {
    throw new MakoEdgeSdkError("function SDK endpoint must be an absolute URL");
  }
  const localHttp =
    endpoint.protocol === "http:" &&
    ["localhost", "127.0.0.1", "host.docker.internal", "host.containers.internal"].includes(
      endpoint.hostname,
    );
  if (endpoint.protocol !== "https:" && !localHttp) {
    throw new MakoEdgeSdkError("function SDK endpoint must use HTTPS outside local development");
  }
  endpoint.pathname = `${endpoint.pathname.replace(/\/+$/u, "")}/`;
  endpoint.search = "";
  endpoint.hash = "";
  return endpoint;
}

function validateCallerAuthorization(value: string | null): string | null {
  if (value === null) {
    return null;
  }
  if (
    value.length < 16 ||
    value.length > 8_192 ||
    /\s/u.test(value) ||
    value.toLowerCase().startsWith("bearer")
  ) {
    throw new MakoEdgeSdkError("runtime caller authorization is invalid");
  }
  return value;
}

function validateServiceCredential(value: string): string {
  if (
    !value.startsWith("mako_sk.") ||
    value.length < 32 ||
    value.length > 512 ||
    /\s/u.test(value)
  ) {
    throw new MakoEdgeSdkError("attached service credential is invalid");
  }
  return value;
}

function validateBypassReason(value: string): string {
  if (
    value.length < 1 ||
    value.length > 512 ||
    value.trim() !== value ||
    Array.from(value).some((character) => {
      const point = character.codePointAt(0);
      return point !== undefined && (point <= 0x1f || point === 0x7f);
    })
  ) {
    throw new MakoEdgeSdkError("service bypass reason is invalid");
  }
  return value;
}

function validateRequestId(value: string | undefined): string | undefined {
  if (value !== undefined && !/^req_[A-Za-z0-9_-]{4,124}$/u.test(value)) {
    throw new MakoEdgeSdkError("runtime request identifier is invalid");
  }
  return value;
}

function validateApplicationUserId(value: string): void {
  if (!/^usr_[A-Za-z0-9_-]{8,96}$/u.test(value)) {
    throw new MakoEdgeSdkError("application user identifier is invalid");
  }
}

function validateAppMetadataPatch(value: FunctionAppMetadataPatch): void {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new MakoEdgeSdkError("app metadata patch must be a JSON object");
  }
}

function validateDocumentId(value: string): void {
  if (
    value.length < 1 ||
    value.length > 1_024 ||
    value.trim() !== value ||
    Array.from(value).some((character) => {
      const point = character.codePointAt(0);
      return point !== undefined && (point <= 0x1f || point === 0x7f);
    })
  ) {
    throw new MakoEdgeSdkError("document identifier is invalid");
  }
}

const PROJECT_ID = /^prj_[A-Za-z0-9_-]{8,64}$/u;
const ENVIRONMENT_ID = /^env_[A-Za-z0-9_-]{8,64}$/u;
const COLLECTION_ID = /^[a-z][a-z0-9_-]{0,62}$/u;
const ERROR_CODES: readonly string[] = [
  "invalid_request",
  "unauthenticated",
  "permission_denied",
  "not_found",
  "conflict",
  "schema_mismatch",
  "checkpoint_expired",
  "rate_limited",
  "quota_exceeded",
  "unavailable",
  "internal",
];

function validateProjectId(value: string): string {
  if (!PROJECT_ID.test(value)) {
    throw new MakoEdgeSdkError("project identifier is invalid");
  }
  return value;
}

function validateEnvironmentId(value: string): string {
  if (!ENVIRONMENT_ID.test(value)) {
    throw new MakoEdgeSdkError("environment identifier is invalid");
  }
  return value;
}

function validateCollectionId(value: string): string {
  if (!COLLECTION_ID.test(value)) {
    throw new MakoEdgeSdkError("collection identifier is invalid");
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** A conservative boundary guard for the versioned error envelope. */
function isApiErrorEnvelope(value: unknown): value is ApiErrorEnvelope {
  if (!isRecord(value) || value.apiVersion !== "v1" || !isRecord(value.error)) {
    return false;
  }
  const { error } = value;
  return (
    typeof error.code === "string" &&
    ERROR_CODES.includes(error.code) &&
    typeof error.message === "string" &&
    typeof error.requestId === "string" &&
    isRecord(error.retry) &&
    (error.retry.kind === "never" ||
      error.retry.kind === "immediate" ||
      (error.retry.kind === "after_delay" && typeof error.retry.afterMs === "number"))
  );
}

function validateQuery(query: FunctionDocumentQuery): void {
  if (
    query.predicates.length < 1 ||
    query.predicates.length > 16 ||
    query.sort.length > 16 ||
    !Number.isSafeInteger(query.limit) ||
    query.limit < 1 ||
    query.limit > 1_000
  ) {
    throw new MakoEdgeSdkError("document query is invalid");
  }
}

function validateMutation<T extends JsonObject>(mutation: FunctionDocumentMutation<T>): void {
  const revisionMatchesOperation =
    (mutation.operation === "create" && mutation.expectedRevision === null) ||
    (mutation.operation !== "create" &&
      typeof mutation.expectedRevision === "string" &&
      mutation.expectedRevision.length > 0);
  if (
    mutation.mutationId.length < 16 ||
    mutation.mutationId.length > 200 ||
    !Number.isSafeInteger(mutation.schemaVersion) ||
    mutation.schemaVersion < 1 ||
    !revisionMatchesOperation ||
    typeof mutation.body !== "object" ||
    mutation.body === null ||
    Array.isArray(mutation.body)
  ) {
    throw new MakoEdgeSdkError("document mutation is invalid");
  }
}
