/** Caller-aware SDK for Mako Cloud edge functions. */

export {
  MakoCallerIdentityRequiredError,
  MakoEdgeSdkError,
  createFunctionClient,
  createFunctionClientFromRequest,
  createServiceClient,
  PACKAGE_NAME,
  type FunctionAppMetadataPatch,
  type FunctionAppMetadataResult,
  type FunctionAuthClient,
  type FunctionClient,
  type FunctionClientOptions,
  type FunctionDocument,
  type FunctionDocumentClient,
  type FunctionDocumentMutation,
  type FunctionDocumentMutationResult,
  type FunctionDocumentQuery,
  type FunctionDocumentQueryPage,
  type JsonObject,
  type RuntimeFunctionClientOptions,
  type ServiceFunctionClient,
  type ServiceFunctionClientOptions,
  type ServiceUserClient,
} from "./client.js";
