// Generated by packages/edge-sdk/scripts/build-runtime-module.mjs -- do not edit.
//
// The edge SDK as the pinned runtime supplies it to a user worker: the emitted
// JavaScript of packages/edge-sdk/src/client.ts, which imports nothing. The
// supervisor writes this source into the worker directory and maps the bare
// specifier "@mako-cloud/edge-sdk" onto it.
//
// It is a string rather than a module because the runtime serves the main
// worker from an eszip: only the module graph reaches the container, and the
// supervisor needs the source text, not the exports.

export const EDGE_SDK_SOURCE = `export const PACKAGE_NAME = "@mako-cloud/edge-sdk";
export class MakoEdgeSdkError extends Error {
    name = "MakoEdgeSdkError";
    code;
    requestId;
    retry;
    status;
    constructor(message, options = {}) {
        super(message);
        if (options.apiError !== undefined) {
            this.code = options.apiError.error.code;
            this.requestId = options.apiError.error.requestId;
            this.retry = options.apiError.error.retry;
        }
        if (options.status !== undefined) {
            this.status = options.status;
        }
    }
}
export class MakoCallerIdentityRequiredError extends MakoEdgeSdkError {
    name = "MakoCallerIdentityRequiredError";
}
/**
 * Creates a tenant-bound client whose auth and document calls always forward
 * the verified invoking identity. Public invocations fail closed on first use.
 */
export function createFunctionClient(options) {
    const transport = new MakoTransport(options, {
        kind: "caller",
        value: validateCallerAuthorization(options.callerAuthorization),
    });
    return {
        auth: {
            getUser: () => transport.request("auth/user", "GET"),
            signOut: () => transport.request("auth/signout", "POST"),
        },
        documents: (collectionId) => new DocumentClient(transport, "collections", validateCollectionId(collectionId)),
    };
}
/** Creates the default caller client directly from the trusted runtime headers. */
export function createFunctionClientFromRequest(options) {
    const callerAuthorization = options.request.headers.get("x-mako-caller-authorization");
    const requestId = options.request.headers.get("x-mako-request-id") ?? undefined;
    return createFunctionClient({
        endpoint: options.endpoint,
        projectId: options.projectId,
        environmentId: options.environmentId,
        callerAuthorization,
        ...(requestId === undefined ? {} : { requestId }),
        ...(options.fetch === undefined ? {} : { fetch: options.fetch }),
    });
}
/**
 * Explicitly creates a privileged document client from an attached service
 * credential. The dedicated service route verifies scope and audits the reason.
 */
export function createServiceClient(options) {
    const configuredReason = validateBypassReason(options.reason);
    const transport = new MakoTransport(options, {
        kind: "service",
        value: validateServiceCredential(options.serviceCredential),
        reason: configuredReason,
    });
    return {
        documents: (collectionId) => new DocumentClient(transport, "service/collections", validateCollectionId(collectionId)),
        users: {
            getAppMetadata: async (userId, reason) => {
                validateApplicationUserId(userId);
                const bypassReason = reason === undefined ? configuredReason : validateBypassReason(reason);
                return transport.request(\`service/users/\${encodeURIComponent(userId)}/app-metadata\`, "GET", undefined, { "X-Mako-Bypass-Reason": bypassReason });
            },
            setAppMetadata: async (userId, patch, options) => {
                validateApplicationUserId(userId);
                validateAppMetadataPatch(patch);
                const settings = typeof options === "string" ? { reason: options } : (options ?? {});
                const bypassReason = settings.reason === undefined ? configuredReason : validateBypassReason(settings.reason);
                const expected = settings.expectedAuthorizationEpoch;
                if (expected !== undefined && (!Number.isSafeInteger(expected) || expected < 0)) {
                    throw new MakoEdgeSdkError("expected authorization epoch must be a non-negative integer");
                }
                const body = {
                    reason: bypassReason,
                    appMetadata: patch,
                    ...(expected === undefined ? {} : { expectedAuthorizationEpoch: expected }),
                };
                return transport.request(\`service/users/\${encodeURIComponent(userId)}/app-metadata\`, "POST", body, { "X-Mako-Bypass-Reason": bypassReason });
            },
        },
    };
}
class DocumentClient {
    #transport;
    #routePrefix;
    #collectionId;
    constructor(transport, routePrefix, collectionId) {
        this.#transport = transport;
        this.#routePrefix = routePrefix;
        this.#collectionId = collectionId;
    }
    async get(documentId) {
        const path = this.#documentPath(documentId);
        try {
            return await this.#transport.request(path, "GET");
        }
        catch (error) {
            if (error instanceof MakoEdgeSdkError && error.status === 404) {
                return null;
            }
            throw error;
        }
    }
    query(query) {
        validateQuery(query);
        return this.#transport.request(\`\${this.#routePrefix}/\${encodeURIComponent(this.#collectionId)}/documents/query\`, "POST", query);
    }
    mutate(documentId, mutation) {
        validateMutation(mutation);
        return this.#transport.request(this.#documentPath(documentId), "POST", mutation, { "Idempotency-Key": mutation.mutationId });
    }
    #documentPath(documentId) {
        validateDocumentId(documentId);
        return \`\${this.#routePrefix}/\${encodeURIComponent(this.#collectionId)}/documents/\${encodeURIComponent(documentId)}\`;
    }
}
class MakoTransport {
    #endpoint;
    #projectId;
    #environmentId;
    #credential;
    #requestId;
    #fetch;
    constructor(options, credential) {
        this.#endpoint = parseEndpoint(options.endpoint);
        this.#projectId = validateProjectId(options.projectId);
        this.#environmentId = validateEnvironmentId(options.environmentId);
        this.#credential = credential;
        this.#requestId = validateRequestId(options.requestId);
        this.#fetch = options.fetch ?? globalThis.fetch;
    }
    async request(path, method, body, extraHeaders = {}) {
        if (this.#credential.kind === "caller" && this.#credential.value === null) {
            throw new MakoCallerIdentityRequiredError("this operation requires an authenticated function caller");
        }
        const headers = new Headers({ Accept: "application/json" });
        if (this.#credential.kind === "caller") {
            headers.set("Authorization", \`Bearer \${this.#credential.value}\`);
        }
        else {
            headers.set("X-Mako-Service-Key", this.#credential.value);
            headers.set("X-Mako-Bypass-Reason", this.#credential.reason);
        }
        if (body !== undefined) {
            headers.set("Content-Type", "application/json");
        }
        if (this.#requestId !== undefined) {
            headers.set("X-Mako-Request-Id", this.#requestId);
        }
        // Per-call headers are set last so a call can narrow a default, such as
        // the bypass reason a single privileged write is audited under.
        for (const [name, value] of Object.entries(extraHeaders)) {
            headers.set(name, value);
        }
        let encodedBody;
        try {
            encodedBody = body === undefined ? undefined : JSON.stringify(body);
        }
        catch {
            throw new MakoEdgeSdkError("function SDK request is not JSON serializable");
        }
        let response;
        try {
            const requestInit = { method, headers };
            if (encodedBody !== undefined) {
                requestInit.body = encodedBody;
            }
            response = await this.#fetch(new Request(this.#url(path), requestInit));
        }
        catch {
            throw new MakoEdgeSdkError("Mako service is unavailable");
        }
        if (!response.ok) {
            const responseBody = await response.json().catch(() => null);
            if (isApiErrorEnvelope(responseBody)) {
                throw new MakoEdgeSdkError(responseBody.error.message, {
                    apiError: responseBody,
                    status: response.status,
                });
            }
            throw new MakoEdgeSdkError("Mako service request failed", { status: response.status });
        }
        if (response.status === 204) {
            return undefined;
        }
        try {
            return (await response.json());
        }
        catch {
            throw new MakoEdgeSdkError("Mako service returned an invalid response", {
                status: response.status,
            });
        }
    }
    #url(path) {
        return new URL(\`v1/projects/\${encodeURIComponent(this.#projectId)}/environments/\${encodeURIComponent(this.#environmentId)}/\${path}\`, this.#endpoint);
    }
}
function parseEndpoint(value) {
    let endpoint;
    try {
        endpoint = new URL(value);
    }
    catch {
        throw new MakoEdgeSdkError("function SDK endpoint must be an absolute URL");
    }
    const localHttp = endpoint.protocol === "http:" &&
        ["localhost", "127.0.0.1", "host.docker.internal", "host.containers.internal"].includes(endpoint.hostname);
    if (endpoint.protocol !== "https:" && !localHttp) {
        throw new MakoEdgeSdkError("function SDK endpoint must use HTTPS outside local development");
    }
    endpoint.pathname = \`\${endpoint.pathname.replace(/\\/+$/u, "")}/\`;
    endpoint.search = "";
    endpoint.hash = "";
    return endpoint;
}
function validateCallerAuthorization(value) {
    if (value === null) {
        return null;
    }
    if (value.length < 16 ||
        value.length > 8_192 ||
        /\\s/u.test(value) ||
        value.toLowerCase().startsWith("bearer")) {
        throw new MakoEdgeSdkError("runtime caller authorization is invalid");
    }
    return value;
}
function validateServiceCredential(value) {
    if (!value.startsWith("mako_sk.") ||
        value.length < 32 ||
        value.length > 512 ||
        /\\s/u.test(value)) {
        throw new MakoEdgeSdkError("attached service credential is invalid");
    }
    return value;
}
function validateBypassReason(value) {
    if (value.length < 1 ||
        value.length > 512 ||
        value.trim() !== value ||
        Array.from(value).some((character) => {
            const point = character.codePointAt(0);
            return point !== undefined && (point <= 0x1f || point === 0x7f);
        })) {
        throw new MakoEdgeSdkError("service bypass reason is invalid");
    }
    return value;
}
function validateRequestId(value) {
    if (value !== undefined && !/^req_[A-Za-z0-9_-]{4,124}$/u.test(value)) {
        throw new MakoEdgeSdkError("runtime request identifier is invalid");
    }
    return value;
}
function validateApplicationUserId(value) {
    if (!/^usr_[A-Za-z0-9_-]{8,96}$/u.test(value)) {
        throw new MakoEdgeSdkError("application user identifier is invalid");
    }
}
function validateAppMetadataPatch(value) {
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
        throw new MakoEdgeSdkError("app metadata patch must be a JSON object");
    }
}
function validateDocumentId(value) {
    if (value.length < 1 ||
        value.length > 1_024 ||
        value.trim() !== value ||
        Array.from(value).some((character) => {
            const point = character.codePointAt(0);
            return point !== undefined && (point <= 0x1f || point === 0x7f);
        })) {
        throw new MakoEdgeSdkError("document identifier is invalid");
    }
}
const PROJECT_ID = /^prj_[A-Za-z0-9_-]{8,64}$/u;
const ENVIRONMENT_ID = /^env_[A-Za-z0-9_-]{8,64}$/u;
const COLLECTION_ID = /^[a-z][a-z0-9_-]{0,62}$/u;
const ERROR_CODES = [
    "invalid_request",
    "unauthenticated",
    "permission_denied",
    "not_found",
    "conflict",
    "schema_mismatch",
    "checkpoint_expired",
    "rate_limited",
    "quota_exceeded",
    "unavailable",
    "internal",
];
function validateProjectId(value) {
    if (!PROJECT_ID.test(value)) {
        throw new MakoEdgeSdkError("project identifier is invalid");
    }
    return value;
}
function validateEnvironmentId(value) {
    if (!ENVIRONMENT_ID.test(value)) {
        throw new MakoEdgeSdkError("environment identifier is invalid");
    }
    return value;
}
function validateCollectionId(value) {
    if (!COLLECTION_ID.test(value)) {
        throw new MakoEdgeSdkError("collection identifier is invalid");
    }
    return value;
}
function isRecord(value) {
    return typeof value === "object" && value !== null && !Array.isArray(value);
}
/** A conservative boundary guard for the versioned error envelope. */
function isApiErrorEnvelope(value) {
    if (!isRecord(value) || value.apiVersion !== "v1" || !isRecord(value.error)) {
        return false;
    }
    const { error } = value;
    return (typeof error.code === "string" &&
        ERROR_CODES.includes(error.code) &&
        typeof error.message === "string" &&
        typeof error.requestId === "string" &&
        isRecord(error.retry) &&
        (error.retry.kind === "never" ||
            error.retry.kind === "immediate" ||
            (error.retry.kind === "after_delay" && typeof error.retry.afterMs === "number")));
}
/**
 * Refuse a query the API would refuse, and say which rule it broke.
 *
 * These are the platform's own bounds, checked here so a function fails at
 * the call rather than on the wire. One message for six different mistakes
 * was worse than no check at all: the commonest of them -- a query with no
 * predicate, because every query must be served by an index and a query that
 * names no field names no index -- is exactly the one a caller is least
 * likely to guess from "document query is invalid".
 */
function validateQuery(query) {
    if (query.predicates.length < 1) {
        throw new MakoEdgeSdkError("document query needs at least one predicate: every query is served by an index, and a query that names no field names no index");
    }
    if (query.predicates.length > 16) {
        throw new MakoEdgeSdkError("document query allows at most 16 predicates");
    }
    if (query.sort.length > 16) {
        throw new MakoEdgeSdkError("document query allows at most 16 sort keys");
    }
    if (!Number.isSafeInteger(query.limit) || query.limit < 1 || query.limit > 1_000) {
        throw new MakoEdgeSdkError("document query limit must be a whole number from 1 to 1000");
    }
}
function validateMutation(mutation) {
    const revisionMatchesOperation = (mutation.operation === "create" && mutation.expectedRevision === null) ||
        (mutation.operation !== "create" &&
            typeof mutation.expectedRevision === "string" &&
            mutation.expectedRevision.length > 0);
    if (mutation.mutationId.length < 16 || mutation.mutationId.length > 200) {
        throw new MakoEdgeSdkError("document mutation id must be 16 to 200 characters");
    }
    if (!Number.isSafeInteger(mutation.schemaVersion) || mutation.schemaVersion < 1) {
        throw new MakoEdgeSdkError("document mutation schema version must be a whole number above 0");
    }
    if (!revisionMatchesOperation) {
        throw new MakoEdgeSdkError(mutation.operation === "create"
            ? "a create names no expected revision: pass null"
            : \`an \${mutation.operation} names the revision it read: pass the document's revision\`);
    }
    if (typeof mutation.body !== "object" || mutation.body === null || Array.isArray(mutation.body)) {
        throw new MakoEdgeSdkError("document mutation body must be a JSON object");
    }
}
`;
